image: condaforge/mambaforge:22.9.0-1

tasks:

  - name: main

    init: |
      echo "Building development environment..."
      mamba env create -f environment.yml
      echo "Development environment ready!"

    command: |
      echo "Activating the environment..."
      conda activate recpulse
      pre-commit install
      yes | mypy --install-types
