name: recpulse
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pydantic=2.0.3
  - make=4.3
  - pytest=7.4.3
  - black=23.10.1
  - numpy=1.26.0
  - matplotlib=3.8.0
  - networkx=3.2.1
  - pre-commit=3.6.0