[tool.black]
line-length = 100
target-version = ["py310", "py311", "py312"]

[tool.isort]
profile = "black"
line_length = 100

[tool.pydocstyle]
convention = "google"
# ignore requirements for module docstring format
add-ignore = "D205"
